In [1]:
import pandas as pd

df = pd.read_csv('/Users/ellipsis.../Desktop/Datafiniti_Pizza_Restaurants_and_the_Pizza_They_Sell_May19.csv')

In [2]:
df.head()

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,keys,latitude,...,menus.currency,menus.dateSeen,menus.description,menus.name,name,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province
0,AVz3Y-7h3D1zeR_xDAqm,2017-06-30T05:05:40Z,2019-05-01T15:43:09Z,4203 E Kiehl Ave,"Pizza,Restaurant,American restaurants,Pizza Pl...",Accommodation & Food Services,Sherwood,US,us/ar/sherwood/4203ekiehlave/-1051391616,34.832300,...,USD,"2018-05-01T04:25:37.197Z,2018-04-16T04:36:02.3...",NaN,Cheese Pizza,Shotgun Dans Pizza,72120,USD,0,25,AR
1,AVweGPFF_7pvs4fzAAzQ,2016-04-02T04:02:49Z,2019-05-01T15:27:50Z,25 E Camelback Rd,"Pizza,Pizza Place,Restaurants",Accommodation & Food Services,Phoenix,US,us/az/phoenix/25ecamelbackrd/-727422936,33.509266,...,USD,"2018-03-03T02:38:06.381Z,2018-01-18T20:18:10.0...",NaN,Pizza Cookie,Sauce Pizza Wine,85012,USD,0,25,AZ
2,AVwdRGa9_7pvs4fz4E3K,2016-03-03T18:39:49Z,2019-05-01T12:52:25Z,3703 Paxton Ave,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,Cincinnati,US,us/oh/cincinnati/3703paxtonave/-619797122,39.144883,...,USD,"2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...",a saucelessampcomma double cheese pizza with a...,Pizza Blanca,Mios Pizzeria,45209,USD,0,25,OH
3,AVwdX4psIN2L1WUfvJB1,2016-03-29T05:08:59Z,2019-05-01T12:52:20Z,30495 John R Rd,"Pizza,Carry-out food,Pizza Place,Restaurants",Accommodation & Food Services,Madison Heights,US,us/mi/madisonheights/30495johnrrd/-874863116,42.516669,...,USD,"2016-10-20T21:50:02Z,2016-03-29T05:08:59Z",NaN,Small Pizza,Hungry Howies Pizza,48071,USD,25,40,MI
4,AVwdaeTtkufWRAb55pSH,2016-03-31T02:34:04Z,2019-05-01T12:50:45Z,3600 Eastern Ave,"Pizza,American restaurants,Pizza Place,Pizza e...",Accommodation & Food Services,Baltimore,US,us/md/baltimore/3600easternave/-1270965359,39.286630,...,USD,2016-03-31T02:34:04Z,NaN,Pizza Sub,Spartan Pizzeria,21224,USD,0,25,MD

In [3]:
df.drop(df.columns[[8, 11, 12, 13, 19, 20, 21, 22]], axis=1, inplace=True)
df

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVz3Y-7h3D1zeR_xDAqm,2017-06-30T05:05:40Z,2019-05-01T15:43:09Z,4203 E Kiehl Ave,"Pizza,Restaurant,American restaurants,Pizza Pl...",Accommodation & Food Services,Sherwood,US,34.832300,-92.183800,USD,"2018-05-01T04:25:37.197Z,2018-04-16T04:36:02.3...",NaN,Cheese Pizza,Shotgun Dans Pizza,AR
1,AVweGPFF_7pvs4fzAAzQ,2016-04-02T04:02:49Z,2019-05-01T15:27:50Z,25 E Camelback Rd,"Pizza,Pizza Place,Restaurants",Accommodation & Food Services,Phoenix,US,33.509266,-112.073044,USD,"2018-03-03T02:38:06.381Z,2018-01-18T20:18:10.0...",NaN,Pizza Cookie,Sauce Pizza Wine,AZ
2,AVwdRGa9_7pvs4fz4E3K,2016-03-03T18:39:49Z,2019-05-01T12:52:25Z,3703 Paxton Ave,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,Cincinnati,US,39.144883,-84.432685,USD,"2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...",a saucelessampcomma double cheese pizza with a...,Pizza Blanca,Mios Pizzeria,OH
3,AVwdX4psIN2L1WUfvJB1,2016-03-29T05:08:59Z,2019-05-01T12:52:20Z,30495 John R Rd,"Pizza,Carry-out food,Pizza Place,Restaurants",Accommodation & Food Services,Madison Heights,US,42.516669,-83.106630,USD,"2016-10-20T21:50:02Z,2016-03-29T05:08:59Z",NaN,Small Pizza,Hungry Howies Pizza,MI
4,AVwdaeTtkufWRAb55pSH,2016-03-31T02:34:04Z,2019-05-01T12:50:45Z,3600 Eastern Ave,"Pizza,American restaurants,Pizza Place,Pizza e...",Accommodation & Food Services,Baltimore,US,39.286630,-76.566984,USD,2016-03-31T02:34:04Z,NaN,Pizza Sub,Spartan Pizzeria,MD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AVwdKXFYByjofQCxmIyZ,2016-03-21T00:12:46Z,2018-01-08T10:25:27Z,1126 E Lovejoy St,Pizza Place,Accommodation & Food Services,Buffalo,US,42.889759,-78.806747,USD,"2017-12-11T12:44:00.000Z,2016-03-21T00:13:00.0...",NaN,Super Steak Pizza,Carbone's Pizzeria,NY
9996,AVwdKXFYByjofQCxmIyZ,2016-03-21T00:12:46Z,2018-01-08T10:25:27Z,1126 E Lovejoy St,Pizza Place,Accommodation & Food Services,Buffalo,US,42.889759,-78.806747,USD,2017-12-11T12:44:00.000Z,NaN,Large Cheese & 1 Item Pizza,Carbone's Pizzeria,NY
9997,AVz6kzsQFcQ3k02bDhwQ,2017-06-30T19:56:11Z,2018-01-07T10:51:29Z,3641 E Main St,"Pizza Place,Restaurants",Accommodation & Food Services,Saint Charles,US,41.921300,-88.275300,USD,"2017-12-10T18:55:00.000Z,2017-10-28T21:52:00.000Z",NaN,"Individual 6"" Pepperoni Stuffed Deep Dish Pizza",Giordano's Pizza,IL
9998,AVz6kzsQFcQ3k02bDhwQ,2017-06-30T19:56:11Z,2018-01-07T10:51:29Z,3641 E Main St,"Pizza Place,Restaurants",Accommodation & Food Services,Saint Charles,US,41.921300,-88.275300,USD,"2017-12-10T18:55:00.000Z,2017-10-28T21:52:00.000Z",NaN,"Individual 6"" Cheese Stuffed Deep Dish Pizza",Giordano's Pizza,IL
9999,AVwdG9zTkufWRAb52Y2A,2015-10-23T01:57:27Z,2018-01-04T17:57:59Z,7460 W Lake Mead Blvd,"Pizza Place,Restaurant,Fast Food,Pizza",Accommodation & Food Services,Las Vegas,US,36.196180,-115.256240,USD,"2017-12-08T19:07:00.000Z,2017-10-28T22:35:00.000Z",NaN,King Arthur's Supreme Pizza,Round Table Pizza,NV

In [4]:
df = df.rename(
    {
        'country': 'cuisines',
        'primaryCategories': 'menus.category'
    },
    axis=1
)

In [5]:
df.head()

,id,dateAdded,dateUpdated,address,categories,menus.category,city,cuisines,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVz3Y-7h3D1zeR_xDAqm,2017-06-30T05:05:40Z,2019-05-01T15:43:09Z,4203 E Kiehl Ave,"Pizza,Restaurant,American restaurants,Pizza Pl...",Accommodation & Food Services,Sherwood,US,34.832300,-92.183800,USD,"2018-05-01T04:25:37.197Z,2018-04-16T04:36:02.3...",NaN,Cheese Pizza,Shotgun Dans Pizza,AR
1,AVweGPFF_7pvs4fzAAzQ,2016-04-02T04:02:49Z,2019-05-01T15:27:50Z,25 E Camelback Rd,"Pizza,Pizza Place,Restaurants",Accommodation & Food Services,Phoenix,US,33.509266,-112.073044,USD,"2018-03-03T02:38:06.381Z,2018-01-18T20:18:10.0...",NaN,Pizza Cookie,Sauce Pizza Wine,AZ
2,AVwdRGa9_7pvs4fz4E3K,2016-03-03T18:39:49Z,2019-05-01T12:52:25Z,3703 Paxton Ave,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,Cincinnati,US,39.144883,-84.432685,USD,"2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...",a saucelessampcomma double cheese pizza with a...,Pizza Blanca,Mios Pizzeria,OH
3,AVwdX4psIN2L1WUfvJB1,2016-03-29T05:08:59Z,2019-05-01T12:52:20Z,30495 John R Rd,"Pizza,Carry-out food,Pizza Place,Restaurants",Accommodation & Food Services,Madison Heights,US,42.516669,-83.106630,USD,"2016-10-20T21:50:02Z,2016-03-29T05:08:59Z",NaN,Small Pizza,Hungry Howies Pizza,MI
4,AVwdaeTtkufWRAb55pSH,2016-03-31T02:34:04Z,2019-05-01T12:50:45Z,3600 Eastern Ave,"Pizza,American restaurants,Pizza Place,Pizza e...",Accommodation & Food Services,Baltimore,US,39.286630,-76.566984,USD,2016-03-31T02:34:04Z,NaN,Pizza Sub,Spartan Pizzeria,MD

In [22]:
values3 = df['dateAdded'].head(3).tolist()
print(values3)

# values3 = ", ".join(map(str, values3))

['2017-06-30T05:05:40Z', '2016-04-02T04:02:49Z', '2016-03-03T18:39:49Z']

In [18]:
df[['city', 'latitude']].dtypes

city         object
latitude    float64
dtype: object

In [23]:
df.describe()

           latitude     longitude
count  10000.000000  10000.000000
mean      38.371895    -90.063800
std        4.573537     17.340379
min       21.421326   -157.802443
25%       34.422946   -104.801126
50%       40.118880    -82.909949
75%       40.905048    -75.194741
max       64.850500    -71.946170

In [24]:
df.dropna()

,id,dateAdded,dateUpdated,address,categories,menus.category,city,cuisines,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
2,AVwdRGa9_7pvs4fz4E3K,2016-03-03T18:39:49Z,2019-05-01T12:52:25Z,3703 Paxton Ave,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,Cincinnati,US,39.144883,-84.432685,USD,"2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...",a saucelessampcomma double cheese pizza with a...,Pizza Blanca,Mios Pizzeria,OH
12,AVwchRVZkufWRAb5wDIV,2016-03-29T04:47:31Z,2019-05-01T12:42:34Z,4061 28th St SE,"Restaurant,Italian Restaurant,Pizza Place,Ital...",Accommodation & Food Services,Grand Rapids,US,42.912878,-85.566939,USD,"2018-04-26T21:25:35.237Z,2018-06-05T01:35:19.2...",Prosciutto arugula and shaved Parmesan drizzle...,Prosciutto Arugula Pizza,Carrabbas Italian Grill,MI
15,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Topped with mozzarellaampcomma feta and ricotta,Three Cheese Pizza,Domenicos Jr,CA
16,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Includes 1 toppingampcomma additional toppings...,Pizza Sandwich,Domenicos Jr,CA
17,AVwc2xOokufWRAb5zu4_,2016-05-24T00:41:59Z,2019-05-01T12:34:44Z,965 N Resler Dr,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,El Paso,US,31.862409,-106.558431,USD,"2018-05-14T18:17:05.194Z,2018-04-02T12:17:58.5...",pepperoni or cheese original round no limit ca...,HotNReady Large Pizza,Little Caesars Pizza,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9951,AVwczFSkIN2L1WUfpAaH,2016-03-29T05:03:31Z,2018-01-23T23:18:35Z,1001A E 162nd St,Pizza Place,Accommodation & Food Services,South Holland,US,41.600588,-87.592803,USD,"2016-03-29T05:04:00.000Z,2016-06-14T02:16:00.000Z",Three medium three topping pizzas,Medium Pizza Offers,Papa John's Pizza,IL
9954,AVwdhHzjkufWRAb56rCx,2015-10-22T19:25:43Z,2018-01-23T23:08:17Z,301 S Blakely St,"Pizza Place,Restaurants",Accommodation & Food Services,Scranton,US,41.419300,-75.632600,USD,2016-04-08T09:28:16Z,"Ground beef, crispy bacon, and american cheese...",Bacon Cheeseburger Pizza,Grande Pizza,PA
9984,AVwcsKIzkufWRAb5x-L4,2016-03-21T00:13:52Z,2018-01-09T12:21:49Z,109-5 Capcom Ave,"Italian Restaurant,Pizza Place,Italian Restaur...",Accommodation & Food Services,Wake Forest,US,35.950552,-78.528608,USD,2016-03-21T00:14:00.000Z,"Ricotta, mozzarella, green peppers, mushroom, ...",Vegetarian Pizza,Bella Italia,NC
9985,AVwdqxZ4IN2L1WUfyGGx,2016-03-28T05:53:23Z,2018-01-09T10:28:05Z,59 Marble Ave,"Pizza Place,Restaurant",Accommodation & Food Services,Pleasantville,US,41.131494,-73.790872,USD,"2016-03-28T05:53:00.000Z,2016-08-03T21:13:00.000Z","Maple, syrup, fresh herbs",Chicken and Waffle Pizza,Wood and Fire,NY
9989,AVwdKXFYByjofQCxmIyZ,2016-03-21T00:12:46Z,2018-01-08T10:25:27Z,1126 E Lovejoy St,Pizza Place,Accommodation & Food Services,Buffalo,US,42.889759,-78.806747,USD,"2016-03-21T00:13:00.000Z,2016-05-03T09:20:00.000Z",With pizza sauce,Pizza Logs (5),Carbone's Pizzeria,NY

In [27]:

df[
    (df['name'] == 'Domenicos Jr') & 
    (df['city'] == 'Glendora') & 
    (df['province'] == 'CA')
]

,id,dateAdded,dateUpdated,address,categories,menus.category,city,cuisines,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
14,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,"2018-02-18T15:21:05.726Z,2018-02-27T05:14:30.5...",NaN,Three Cheese Pizza,Domenicos Jr,CA
15,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Topped with mozzarellaampcomma feta and ricotta,Three Cheese Pizza,Domenicos Jr,CA
16,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Includes 1 toppingampcomma additional toppings...,Pizza Sandwich,Domenicos Jr,CA

In [80]:
# df[
#     (df['name'] == 'Domenicos Jr') | 
#     (
#         (df['city'] == 'Wake Forest') & 
#         ~df['menus.description'].isin(['fresh herbs', 'mushroom'])
#     )
# ]

result = df[
    (df['name'] == 'Domenicos Jr') |
    (
        (df['city'] == 'Wake Forest') &
        ~df['menus.description'].str.contains("mushroom|fresh herbs", case=False, na=False)
    )
]

result

,id,dateAdded,dateUpdated,address,categories,menus.category,city,cuisines,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province,datetime,date
14,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,"2018-02-18T15:21:05.726Z,2018-02-27T05:14:30.5...",NaN,Three Cheese Pizza,Domenicos Jr,CA,2015-10-21 17:51:11+00:00,2015-10-21 17:51:11+00:00
15,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Topped with mozzarellaampcomma feta and ricotta,Three Cheese Pizza,Domenicos Jr,CA,2015-10-21 17:51:11+00:00,2015-10-21 17:51:11+00:00
16,AVwc7s1wIN2L1WUfqehD,2015-10-21T17:51:11Z,2019-05-01T12:42:05Z,146 N Glendora Ave,"Pizza,Restaurant,Pizza Place",Accommodation & Food Services,Glendora,US,34.137502,-117.865331,USD,2018-05-11T22:26:10.666Z,Includes 1 toppingampcomma additional toppings...,Pizza Sandwich,Domenicos Jr,CA,2015-10-21 17:51:11+00:00,2015-10-21 17:51:11+00:00
369,AVwdMqWBByjofQCxmiZ3,2016-03-21T00:13:27Z,2019-04-19T09:28:14Z,12277 Capital Blvd,"Pizza,American restaurants,Pizza Place,Restaur...",Accommodation & Food Services,Wake Forest,US,35.981014,-78.540873,USD,2016-03-21T00:13:00.000Z,Available only in medium and large,Stuffed Pizza,PTA Pizza Hoagie,NC,2016-03-21 00:13:27+00:00,2016-03-21 00:13:27+00:00
9981,AVwcsKIzkufWRAb5x-L4,2016-03-21T00:13:52Z,2018-01-09T12:21:49Z,109-5 Capcom Ave,"Italian Restaurant,Pizza Place,Italian Restaur...",Accommodation & Food Services,Wake Forest,US,35.950552,-78.528608,USD,"2017-12-19T14:02:00.000Z,2017-12-10T19:17:00.0...",NaN,Deluxe Pizza,Bella Italia,NC,2016-03-21 00:13:52+00:00,2016-03-21 00:13:52+00:00
9982,AVwcsKIzkufWRAb5x-L4,2016-03-21T00:13:52Z,2018-01-09T12:21:49Z,109-5 Capcom Ave,"Italian Restaurant,Pizza Place,Italian Restaur...",Accommodation & Food Services,Wake Forest,US,35.950552,-78.528608,USD,"2017-12-19T14:02:00.000Z,2017-12-10T19:17:00.0...",NaN,Pizza Roll,Bella Italia,NC,2016-03-21 00:13:52+00:00,2016-03-21 00:13:52+00:00
9983,AVwcsKIzkufWRAb5x-L4,2016-03-21T00:13:52Z,2018-01-09T12:21:49Z,109-5 Capcom Ave,"Italian Restaurant,Pizza Place,Italian Restaur...",Accommodation & Food Services,Wake Forest,US,35.950552,-78.528608,USD,"2017-12-19T14:02:00.000Z,2017-12-10T19:17:00.0...",NaN,Meat Lovers Pizza,Bella Italia,NC,2016-03-21 00:13:52+00:00,2016-03-21 00:13:52+00:00

In [36]:
result = df[~df['menus.currency'].isna()]
result

,id,dateAdded,dateUpdated,address,categories,menus.category,city,cuisines,latitude,longitude,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVz3Y-7h3D1zeR_xDAqm,2017-06-30T05:05:40Z,2019-05-01T15:43:09Z,4203 E Kiehl Ave,"Pizza,Restaurant,American restaurants,Pizza Pl...",Accommodation & Food Services,Sherwood,US,34.832300,-92.183800,USD,"2018-05-01T04:25:37.197Z,2018-04-16T04:36:02.3...",NaN,Cheese Pizza,Shotgun Dans Pizza,AR
1,AVweGPFF_7pvs4fzAAzQ,2016-04-02T04:02:49Z,2019-05-01T15:27:50Z,25 E Camelback Rd,"Pizza,Pizza Place,Restaurants",Accommodation & Food Services,Phoenix,US,33.509266,-112.073044,USD,"2018-03-03T02:38:06.381Z,2018-01-18T20:18:10.0...",NaN,Pizza Cookie,Sauce Pizza Wine,AZ
2,AVwdRGa9_7pvs4fz4E3K,2016-03-03T18:39:49Z,2019-05-01T12:52:25Z,3703 Paxton Ave,"Restaurant,Pizza Place,Restaurants",Accommodation & Food Services,Cincinnati,US,39.144883,-84.432685,USD,"2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...",a saucelessampcomma double cheese pizza with a...,Pizza Blanca,Mios Pizzeria,OH
3,AVwdX4psIN2L1WUfvJB1,2016-03-29T05:08:59Z,2019-05-01T12:52:20Z,30495 John R Rd,"Pizza,Carry-out food,Pizza Place,Restaurants",Accommodation & Food Services,Madison Heights,US,42.516669,-83.106630,USD,"2016-10-20T21:50:02Z,2016-03-29T05:08:59Z",NaN,Small Pizza,Hungry Howies Pizza,MI
4,AVwdaeTtkufWRAb55pSH,2016-03-31T02:34:04Z,2019-05-01T12:50:45Z,3600 Eastern Ave,"Pizza,American restaurants,Pizza Place,Pizza e...",Accommodation & Food Services,Baltimore,US,39.286630,-76.566984,USD,2016-03-31T02:34:04Z,NaN,Pizza Sub,Spartan Pizzeria,MD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AVwdKXFYByjofQCxmIyZ,2016-03-21T00:12:46Z,2018-01-08T10:25:27Z,1126 E Lovejoy St,Pizza Place,Accommodation & Food Services,Buffalo,US,42.889759,-78.806747,USD,"2017-12-11T12:44:00.000Z,2016-03-21T00:13:00.0...",NaN,Super Steak Pizza,Carbone's Pizzeria,NY
9996,AVwdKXFYByjofQCxmIyZ,2016-03-21T00:12:46Z,2018-01-08T10:25:27Z,1126 E Lovejoy St,Pizza Place,Accommodation & Food Services,Buffalo,US,42.889759,-78.806747,USD,2017-12-11T12:44:00.000Z,NaN,Large Cheese & 1 Item Pizza,Carbone's Pizzeria,NY
9997,AVz6kzsQFcQ3k02bDhwQ,2017-06-30T19:56:11Z,2018-01-07T10:51:29Z,3641 E Main St,"Pizza Place,Restaurants",Accommodation & Food Services,Saint Charles,US,41.921300,-88.275300,USD,"2017-12-10T18:55:00.000Z,2017-10-28T21:52:00.000Z",NaN,"Individual 6"" Pepperoni Stuffed Deep Dish Pizza",Giordano's Pizza,IL
9998,AVz6kzsQFcQ3k02bDhwQ,2017-06-30T19:56:11Z,2018-01-07T10:51:29Z,3641 E Main St,"Pizza Place,Restaurants",Accommodation & Food Services,Saint Charles,US,41.921300,-88.275300,USD,"2017-12-10T18:55:00.000Z,2017-10-28T21:52:00.000Z",NaN,"Individual 6"" Cheese Stuffed Deep Dish Pizza",Giordano's Pizza,IL
9999,AVwdG9zTkufWRAb52Y2A,2015-10-23T01:57:27Z,2018-01-04T17:57:59Z,7460 W Lake Mead Blvd,"Pizza Place,Restaurant,Fast Food,Pizza",Accommodation & Food Services,Las Vegas,US,36.196180,-115.256240,USD,"2017-12-08T19:07:00.000Z,2017-10-28T22:35:00.000Z",NaN,King Arthur's Supreme Pizza,Round Table Pizza,NV

In [41]:
type(df['categories'].dtype)
type(df[['categories']].dtypes)

pandas.core.series.Series

In [42]:
df['city'].head(5).mode()

0          Baltimore
1         Cincinnati
2    Madison Heights
3            Phoenix
4           Sherwood
Name: city, dtype: object

In [43]:
taco_bell = df[df['name'] == 'Domenicos Jr']
result = taco_bell['city'].value_counts().head(5)
result

city
Glendora    3
Name: count, dtype: int64

In [51]:
df_1 = df.copy()
df_1['datetime'] = pd.to_datetime(df['dateAdded'])
df_1 = df_1.sort_values(by="datetime", ascending=True)
df_1['dateAdded'].head(5).tolist()

['2014-01-02T03:42:49Z',
 '2014-01-02T03:42:49Z',
 '2014-01-02T05:48:13Z',
 '2014-01-02T05:48:13Z',
 '2014-01-02T05:48:13Z']

In [63]:
# data = df.copy()
data['dateAdded'] = pd.to_datetime(data['dateAdded'])

result = (
    data.groupby(data['dateAdded'].dt.month)['id']
    .nunique()
    .to_frame()
)

result

            id
dateAdded
1          116
2           22
3          494
4          287
5          125
6          525
7          152
8           33
9           67
10         352
11          75
12          37

In [74]:
data['dateAdded'] = pd.to_datetime(data['dateAdded'])
data['dateUpdated'] = pd.to_datetime(data['dateUpdated'])

data['update_delta'] = (data['dateUpdated'] - data['dateAdded']).dt.days

result = (
    data.groupby("city")
    .agg(
        update_delta_mean=("update_delta", "mean"),
        north_latitude=("latitude", "max")
    )
    .reset_index()
)

zep_mean = result.loc[result['city'] == "Baltimore", "update_delta_mean"].iloc[0]

print(result.head())
print(zep_mean)

       city  update_delta_mean  north_latitude
0  Aberdeen         856.000000       39.509636
1   Abilene        1283.000000       32.403556
2  Abingdon         936.000000       36.695998
3  Abington         712.000000       40.123125
4     Akron         666.090909       41.133751
1011.88

In [82]:
pizza = data[data['categories'].str.contains("Pizza", case=False)]

third_index = pizza.iloc[2].name
third_index

2

In [88]:
data['dateAdded'] = pd.to_datetime(data['dateAdded'])
data['dateUpdated'] = pd.to_datetime(data['dateUpdated'])

data['update_delta'] = (data['dateUpdated'] - data['dateAdded']).dt.days

mean_val = data['update_delta'].mean()
median_val = data['update_delta'].median()

print(round(mean_val, 2), round(median_val, 2))

786.91 777.0

In [93]:
data['c_count'] = data['categories'].str.count(',') + 1

filtered = data[data['c_count'] > 2]

result = filtered.groupby('province', as_index=False)['longitude'].min()

result['longitude'] = result['longitude'].round(3)
result

   province  longitude
0        AK   -149.118
1        AR    -94.426
2        AZ   -112.341
3        CA   -122.717
4        CO   -107.882
5        CT    -73.400
6        DE    -75.289
7        FL    -85.223
8        GA    -84.611
9        IA    -93.795
10       ID   -116.794
11       IL    -90.199
12       IN    -87.513
13       KS    -97.244
14       KY    -85.753
15       LA    -92.473
16       MD    -77.529
17       MI    -86.742
18       MN    -93.426
19       MO    -94.586
20       MS    -89.937
21       NC    -82.064
22       NE   -102.890
23       NM   -106.658
24       NV   -119.754
25       NY    -79.036
26       OH    -84.543
27       OK    -97.508
28       OR   -123.118
29       PA    -80.223
30       SC    -82.837
31       SD    -96.751
32       TN    -86.804
33       TX   -106.558
34       UT   -112.040
35       VA    -82.009
36       WA   -123.016
37       WI    -92.758
38       WV    -81.634

In [94]:
result.to_csv('result.csv', sep=';', index=False)

In [97]:
pd.read_csv('result.csv', sep=';').head(5)

  province  longitude
0       AK   -149.118
1       AR    -94.426
2       AZ   -112.341
3       CA   -122.717
4       CO   -107.882